<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="9.3.0" />
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MudBlazor" Version="8.6.0" />
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="OpenIddict.Abstractions" Version="6.3.0" />
		<PackageReference Include="OpenIddict.AspNetCore" Version="6.3.0" />
		<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="6.3.0" />
		<PackageReference Include="OpenIddict.Quartz" Version="6.3.0" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0" />
		<PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Echo.SystemOrchestrator\Echo.SystemOrchestrator.ServiceDefaults\Echo.SystemOrchestrator.ServiceDefaults.csproj" />
	  <ProjectReference Include="..\Echo.Chat.Web.Client\Echo.Chat.Web.Client.csproj" />
	</ItemGroup>

</Project>